# Generated by Django 2.2 on 2019-04-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sequences.Sequence'),
        ),
    ]
